name: benefixs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  retry: ^3.1.2
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


flutter_icons:
  android: true  
  ios: true      
  macos:
    generate: false 
    image_path: "images/ben.jpeg"
  windows:
    generate: false 
    image_path: "images/ben.jpeg"
    icon_size: 48   
  remove_alpha_ios: true  
  
  image_path: "images/ben.jpeg" 

  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "images/ben.jpeg" 

  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Italic.ttf
        - asset: fonts/DMSans-Bold.ttf
      #    style: italic
      #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
